#!/usr/bin/env bash
#
# Deploys the current branch for manual end-to-end testing, then opens
# 3 browser windows:
#   - Chrome (host)   in isolated profile  -> bare URL
#   - Chrome (guest)  in isolated profile  -> URL?room=<ROOM>
#   - Safari (guest)                       -> URL?room=<ROOM>
#
# Modes:
#   (default)  Firebase Hosting preview channel "staging".
#              URL is `https://<project>--staging-*.web.app`. Isolated from
#              production. DOES NOT deploy database.rules.json.
#
#   --live     Live Firebase Hosting (production URL) but ONLY hosting —
#              no database rules. URL is `https://<project>.web.app`,
#              so the QR generated by the host works for guests.
#              WARNING: this REPLACES the live hosting bundle. Use only
#              when you accept that what's testing is what users see.
#
# Override the channel name/expiry via env:
#   STAGING_CHANNEL=alpha STAGING_EXPIRES=2d ./scripts/deploy-staging.sh
#
# Requires: macOS, npx, firebase CLI, Google Chrome, Safari.

set -euo pipefail

cd "$(dirname "$0")/.."

MODE="channel"
if [[ "${1:-}" == "--live" ]]; then
  MODE="live"
fi

CHANNEL="${STAGING_CHANNEL:-staging}"
EXPIRES="${STAGING_EXPIRES:-7d}"

echo "[staging] Type-check"
npm run typecheck

echo "[staging] Tests"
npm test

echo "[staging] Build web bundle"
./scripts/build-web.sh

if [[ "$MODE" == "live" ]]; then
  echo
  echo "[staging] LIVE HOSTING DEPLOY — this replaces production hosting."
  read -r -p "[staging] Confermi il deploy su LIVE hosting (no DB rules)? [y/N] " confirm
  [[ "${confirm:-}" =~ ^[Yy]$ ]] || { echo "[staging] Abortito."; exit 1; }

  set -o pipefail
  firebase deploy --only hosting 2>&1 | tee /dev/tty

  # The live URL is fixed.
  URL="$(node -e "console.log(JSON.parse(require('fs').readFileSync('.firebaserc','utf8')).projects.default)" 2>/dev/null \
    | awk '{print "https://"$1".web.app"}')"
  if [[ -z "${URL:-}" || "${URL}" == "https://.web.app" ]]; then
    URL="https://gameshub-6b1ce.web.app"
  fi
else
  echo "[staging] Deploying to preview channel '$CHANNEL' (expires in $EXPIRES)"
  set -o pipefail
  DEPLOY_OUT="$(firebase hosting:channel:deploy "$CHANNEL" --expires "$EXPIRES" 2>&1 | tee /dev/tty)"

  URL="$(printf '%s\n' "$DEPLOY_OUT" \
    | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' \
    | grep -oE 'https://[a-zA-Z0-9.-]+--'"$CHANNEL"'-[a-zA-Z0-9.-]+\.web\.app' \
    | head -1)"

  if [[ -z "${URL:-}" ]]; then
    echo "[staging] ERROR: could not parse channel URL from firebase output" >&2
    exit 1
  fi
fi

echo
echo "[staging] URL: $URL"
echo

HOST_PROFILE="${TMPDIR:-/tmp}/gameshub-staging-host"
GUEST_PROFILE="${TMPDIR:-/tmp}/gameshub-staging-guest"
mkdir -p "$HOST_PROFILE" "$GUEST_PROFILE"

echo "[staging] Opening Chrome (host) in isolated profile: $HOST_PROFILE"
open -na "Google Chrome" --args \
  --new-window \
  --user-data-dir="$HOST_PROFILE" \
  --no-first-run --no-default-browser-check \
  "$URL"

echo
echo "Crea la stanza nella finestra host appena aperta, poi torna qui."
read -r -p "Inserisci il ROOM ID (6 caratteri): " ROOM
ROOM_UPPER="$(printf '%s' "$ROOM" | tr '[:lower:]' '[:upper:]')"

if [[ ! "$ROOM_UPPER" =~ ^[A-Z0-9]{6}$ ]]; then
  echo "[staging] ERROR: room id non valido: '$ROOM'" >&2
  exit 1
fi

GUEST_URL="${URL}/?room=${ROOM_UPPER}"

echo "[staging] Opening Chrome (guest) on $GUEST_URL"
open -na "Google Chrome" --args \
  --new-window \
  --user-data-dir="$GUEST_PROFILE" \
  --no-first-run --no-default-browser-check \
  "$GUEST_URL"

echo "[staging] Opening Safari (guest) on $GUEST_URL"
osascript <<EOF
tell application "Safari"
  activate
  make new document with properties {URL:"$GUEST_URL"}
end tell
EOF

echo
echo "[staging] Pronti. Chiudi le finestre quando hai finito."
echo
echo "Per ripulire le sessioni dei browser di test:"
echo "  rm -rf \"$HOST_PROFILE\" \"$GUEST_PROFILE\""
echo "Per Safari, svuota i dati del sito da Preferences > Privacy."
