#!/usr/bin/env bash
#
# Deploys the current branch for manual end-to-end testing, then opens
# phone-sized chromeless Chrome windows like `npm run dev:multi`:
#   - 1 host window (slot 0, top-left, isolated profile)
#   - N guest windows, each with its own profile and `cid=pN&name=GiocatoreN`
#     so they join the room automatically.
#
# Usage:
#   npm run deploy:staging                 # preview channel, 4 guests
#   npm run deploy:staging -- 6            # preview channel, 6 guests
#   npm run deploy:staging -- --live       # live hosting, 4 guests
#   npm run deploy:staging -- --live 6     # live hosting, 6 guests
#
# Modes:
#   (default)  Firebase Hosting preview channel "staging".
#              URL is `https://<project>--staging-*.web.app`. Isolated from
#              production hosting; backend/database remain shared.
#              DOES NOT deploy database.rules.json.
#
#   --live     Live Firebase Hosting (production URL) but ONLY hosting —
#              no database rules. URL is `https://<project>.web.app`,
#              so the QR generated by the host works for guests.
#              WARNING: this REPLACES the live hosting bundle. Use only
#              when you accept that what's testing is what users see.
#
# Overrides via env:
#   STAGING_CHANNEL=alpha STAGING_EXPIRES=2d  channel name/expiry
#   GUESTS=6                                  number of guest windows
#   WIN_W=390 WIN_H=800                       window size (px)
#   NAME_PREFIX=Giocatore                     player name prefix
#
# Requires: macOS, npx, firebase CLI, Google Chrome.

set -euo pipefail

cd "$(dirname "$0")/.."

MODE="channel"
if [[ "${1:-}" == "--live" ]]; then
  MODE="live"
  shift
fi

GUESTS="${1:-${GUESTS:-4}}"
WIN_W="${WIN_W:-390}"
WIN_H="${WIN_H:-800}"
NAME_PREFIX="${NAME_PREFIX:-Giocatore}"

CHANNEL="${STAGING_CHANNEL:-staging}"
EXPIRES="${STAGING_EXPIRES:-7d}"

echo "[staging] Type-check"
npm run typecheck

echo "[staging] Tests"
npm test

echo "[staging] Build web bundle"
# Public previews must not embed the local Gemini credential. Built-in and
# custom dictionaries remain available; AI generation requires a server proxy.
./scripts/build-web.sh

if [[ "$MODE" == "live" ]]; then
  echo
  echo "[staging] LIVE HOSTING DEPLOY — this replaces production hosting."
  read -r -p "[staging] Confermi il deploy su LIVE hosting (no DB rules)? [y/N] " confirm
  [[ "${confirm:-}" =~ ^[Yy]$ ]] || { echo "[staging] Abortito."; exit 1; }

  set -o pipefail
  firebase deploy --only hosting 2>&1 | tee /dev/tty

  # The live URL is fixed.
  URL="$(node -e "console.log(JSON.parse(require('fs').readFileSync('.firebaserc','utf8')).projects.default)" 2>/dev/null \
    | awk '{print "https://"$1".web.app"}')"
  if [[ -z "${URL:-}" || "${URL}" == "https://.web.app" ]]; then
    URL="https://gameshub-6b1ce.web.app"
  fi
else
  echo "[staging] Deploying to preview channel '$CHANNEL' (expires in $EXPIRES)"
  set -o pipefail
  DEPLOY_OUT="$(firebase hosting:channel:deploy "$CHANNEL" --expires "$EXPIRES" 2>&1 | tee /dev/tty)"

  URL="$(printf '%s\n' "$DEPLOY_OUT" \
    | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' \
    | grep -oE 'https://[a-zA-Z0-9.-]+--'"$CHANNEL"'-[a-zA-Z0-9.-]+\.web\.app' \
    | head -1)"

  if [[ -z "${URL:-}" ]]; then
    echo "[staging] ERROR: could not parse channel URL from firebase output" >&2
    exit 1
  fi
fi

echo
echo "[staging] URL: $URL"
echo

HOST_PROFILE="${TMPDIR:-/tmp}/gameshub-staging-host"
mkdir -p "$HOST_PROFILE"

echo "[staging] Apro la finestra host ($WIN_W x $WIN_H)"
open -na "Google Chrome" --args \
  --user-data-dir="$HOST_PROFILE" \
  --no-first-run --no-default-browser-check \
  --window-size="$WIN_W,$WIN_H" \
  --window-position="0,60" \
  --app="$URL"

echo
echo "Crea la stanza nella finestra host appena aperta, poi torna qui."
read -r -p "Inserisci il ROOM ID (6 caratteri): " ROOM
ROOM_UPPER="$(printf '%s' "$ROOM" | tr '[:lower:]' '[:upper:]')"

if [[ ! "$ROOM_UPPER" =~ ^[A-Z0-9]{6}$ ]]; then
  echo "[staging] ERROR: room id non valido: '$ROOM'" >&2
  exit 1
fi

echo "[staging] Stanza $ROOM_UPPER — apro $GUESTS guest ($WIN_W x $WIN_H)"

for ((i = 1; i <= GUESTS; i++)); do
  n=$((i + 1)) # host is player 1
  profile="${TMPDIR:-/tmp}/gameshub-staging-p$n"
  mkdir -p "$profile"
  guest_url="$URL/?room=$ROOM_UPPER&cid=p$n&name=$NAME_PREFIX$n"
  # Slot 0 is reserved for the host window opened above.
  x=$(( i * (WIN_W + 14) ))

  echo "[staging]  → $NAME_PREFIX$n ($guest_url)"
  open -na "Google Chrome" --args \
    --user-data-dir="$profile" \
    --no-first-run --no-default-browser-check \
    --window-size="$WIN_W,$WIN_H" \
    --window-position="$x,60" \
    --app="$guest_url"
done

echo
echo "[staging] Pronti. I guest entrano in stanza da soli."
echo "Per ripulire le identità di test:"
echo "  rm -rf ${TMPDIR:-/tmp}/gameshub-staging-host ${TMPDIR:-/tmp}/gameshub-staging-p*"
